# Generated by Django 4.1.3 on 2022-11-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0017_alter_dictionary_owner'),
        ('users', '0005_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='added_dicts',
            field=models.ManyToManyField(to='main_page.dictionary'),
        ),
    ]
