# Generated by Django 4.1.2 on 2022-10-24 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=40)),
                ('tranlsate', models.CharField(max_length=40)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.dictionary')),
            ],
        ),
    ]
