# Generated by Django 4.1.2 on 2022-10-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_rename_tranlsate_translates_translate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='creation_date',
            field=models.DateTimeField(default=None),
        ),
    ]
