# Generated by Django 4.1.2 on 2022-10-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_alter_dictionary_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='creation_date',
            field=models.DateTimeField(default='1970.01.01'),
        ),
    ]
