# Generated by Django 4.1.2 on 2022-11-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_alter_dictionary_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='creation_date',
            field=models.CharField(default='08.11.2022 22:52', max_length=40),
        ),
    ]
