# Generated by Django 4.1.3 on 2022-11-12 10:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_first_name_alter_user_last_name'),
        ('main_page', '0011_alter_dictionary_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='lang_from',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='lang_to',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='translates',
            name='translate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='translates',
            name='word',
            field=models.CharField(max_length=255),
        ),
    ]
