# Generated by Django 4.1.3 on 2022-11-12 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_first_name_alter_user_last_name'),
        ('main_page', '0012_dictionary_owner_alter_dictionary_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='lang_from',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='lang_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
