# Generated by Django 4.1.3 on 2022-11-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0013_alter_dictionary_lang_from_alter_dictionary_lang_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionary',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
