# Generated by Django 4.1.3 on 2022-11-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0014_rename_owner_dictionary_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
