# Generated by Django 4.1.3 on 2022-11-17 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_first_name_alter_user_last_name'),
        ('main_page', '0016_rename_owner_id_dictionary_owner_dictionary_private_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
