# Generated by Django 4.1.3 on 2022-11-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0018_dictionary_level_dictionary_raiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='level',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2, null=True),
        ),
    ]
