# Generated by Django 4.1.2 on 2022-10-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('lang_from', models.CharField(max_length=40)),
                ('lang_to', models.CharField(max_length=40)),
                ('creation_date', models.DateTimeField()),
            ],
        ),
    ]
