# Generated by Django 4.1.2 on 2022-10-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_translates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='lang_from',
            field=models.CharField(default='unknown', max_length=40),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='lang_to',
            field=models.CharField(default='unknown', max_length=40),
        ),
    ]
