# Generated by Django 4.1.2 on 2022-10-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_alter_dictionary_lang_from_alter_dictionary_lang_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='creation_date',
            field=models.DateTimeField(default='24.10.2022'),
        ),
    ]
