# Generated by Django 4.1.2 on 2022-11-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_alter_dictionary_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='creation_date',
            field=models.CharField(default='07.11.2022 16:13', max_length=40),
        ),
    ]
